/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/interview/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn */
        post: operations["turn_v1_interview_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interview/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_v1_interview_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/packs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Builds a small set of interview rounds tailored to the candidate's exact target role and job
         *     description, so the app works for any profession rather than a fixed list of tech rounds.
         */
        post: operations["generate_v1_packs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Roadmap */
        post: operations["roadmap_v1_roadmap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assist
         * @description Writing assist for the Notes drawer and the Cortex notebook. "improve" tidies existing content;
         *     "generate" drafts new content. Always returns HTML limited to tags both editors render.
         */
        post: operations["assist_v1_assist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models Health
         * @description Connection test behind Settings -> Data & AI: pings the chat and scoring models.
         */
        get: operations["models_health_v1_health_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness for the platform (no auth, no Gemini call).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerReview */
        AnswerReview: {
            /** Question */
            question: string;
            /** Answersummary */
            answerSummary: string;
            /** Score */
            score: number;
            /** Feedback */
            feedback: string;
            /** Betteranswer */
            betterAnswer: string;
            /** Expectedanswer */
            expectedAnswer: string;
        };
        /** AssistRequest */
        AssistRequest: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "improve" | "generate";
            /** Text */
            text?: string | null;
            /** Instruction */
            instruction?: string | null;
            /** Contexttitle */
            contextTitle?: string | null;
        };
        /** AssistResult */
        AssistResult: {
            /** Html */
            html: string;
        };
        /** DimensionScore */
        DimensionScore: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Evidence */
            evidence: string;
            /** Feedback */
            feedback: string;
        };
        /**
         * DomainIn
         * @description The field profile (lib/domains in Core), resolved by Core from the catalog.
         */
        DomainIn: {
            /** Id */
            id: string;
            /**
             * Interviewercontext
             * @default
             */
            interviewerContext?: string;
            /**
             * Scoringcontext
             * @default
             */
            scoringContext?: string;
            /**
             * Roundhints
             * @default
             */
            roundHints?: string;
            /**
             * Roadmaphints
             * @default
             */
            roadmapHints?: string;
            /**
             * Version
             * @default 1
             */
            version?: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Error */
            error: string;
        };
        /** GeneratedPack */
        GeneratedPack: {
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Role */
            role: string;
            /**
             * Roundtype
             * @enum {string}
             */
            roundType: "behavioural" | "technical" | "coding" | "hr";
            /** Description */
            description: string;
            /** Durationmin */
            durationMin: number;
            /** Topics */
            topics: string[];
            /** Rubric */
            rubric: string[];
            /** Style */
            style: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Message */
        Message: {
            /**
             * Role
             * @enum {string}
             */
            role: "interviewer" | "candidate";
            /** Text */
            text: string;
        };
        /** ModelCheck */
        ModelCheck: {
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
            /** Ms */
            ms: number;
            /** Error */
            error?: string | null;
        };
        /** ModelsHealth */
        ModelsHealth: {
            /** Ok */
            ok: boolean;
            /** Haskey */
            hasKey: boolean;
            /** Error */
            error?: string | null;
            chat?: components["schemas"]["ModelCheck"] | null;
            scoring?: components["schemas"]["ModelCheck"] | null;
        };
        /** Pack */
        Pack: {
            /** Title */
            title: string;
            /**
             * Company
             * @default
             */
            company?: string;
            /**
             * Role
             * @default
             */
            role?: string;
            /**
             * Roundtype
             * @enum {string}
             */
            roundType: "behavioural" | "technical" | "coding" | "hr";
            /**
             * Description
             * @default
             */
            description?: string;
            /** Topics */
            topics: string[];
            /** Rubric */
            rubric: string[];
            /**
             * Style
             * @default
             */
            style?: string;
        };
        /** PackGenerateRequest */
        PackGenerateRequest: {
            profile: components["schemas"]["Profile"];
            domain: components["schemas"]["DomainIn"];
        };
        /** PacksResult */
        PacksResult: {
            /** Packs */
            packs: components["schemas"]["GeneratedPack"][];
        };
        /**
         * PersonaIn
         * @description The interviewer persona, resolved by Core from its PERSONAS table.
         */
        PersonaIn: {
            /** Name */
            name: string;
            /** Tone */
            tone: string;
        };
        /** Profile */
        Profile: {
            /**
             * Name
             * @default
             */
            name?: string;
            /**
             * Targetrole
             * @default
             */
            targetRole?: string;
            /**
             * Targetcompanies
             * @default
             */
            targetCompanies?: string;
            /**
             * Jobdescription
             * @default
             */
            jobDescription?: string;
            /**
             * Experience
             * @default
             */
            experience?: string;
            /**
             * Resume
             * @default
             */
            resume?: string;
        };
        /** ReportRequest */
        ReportRequest: {
            config: components["schemas"]["SessionConfig"];
            profile: components["schemas"]["Profile"];
            pack: components["schemas"]["Pack"];
            domain: components["schemas"]["DomainIn"];
            /** Interviewername */
            interviewerName: string;
            /**
             * Messages
             * @default []
             */
            messages?: components["schemas"]["Message"][];
            /**
             * Code
             * @default
             */
            code?: string;
        };
        /** ReportResult */
        ReportResult: {
            /** Overall */
            overall: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "Strong Hire" | "Hire" | "Borderline" | "Not Yet";
            /** Summary */
            summary: string;
            /** Strengths */
            strengths: string[];
            /** Topfixes */
            topFixes: string[];
            /** Dimensions */
            dimensions: components["schemas"]["DimensionScore"][];
            /** Answerreviews */
            answerReviews: components["schemas"]["AnswerReview"][];
        };
        /** RoadmapItem */
        RoadmapItem: {
            /** Week */
            week: number;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Focus */
            focus: string;
        };
        /** RoadmapRequest */
        RoadmapRequest: {
            profile: components["schemas"]["Profile"];
            domain: components["schemas"]["DomainIn"];
            /** Weeks */
            weeks?: number | null;
            /**
             * Digests
             * @default []
             */
            digests?: {
                [key: string]: unknown;
            }[];
        };
        /** RoadmapResult */
        RoadmapResult: {
            /** Summary */
            summary: string;
            /** Items */
            items: components["schemas"]["RoadmapItem"][];
        };
        /** SessionConfig */
        SessionConfig: {
            /**
             * Persona
             * @enum {string}
             */
            persona: "friendly" | "neutral" | "tough";
            /** Durationmin */
            durationMin: number;
            /**
             * Pressure
             * @default false
             */
            pressure?: boolean;
            /** Questioncount */
            questionCount?: number | null;
        };
        /** TurnRequest */
        TurnRequest: {
            config: components["schemas"]["SessionConfig"];
            profile: components["schemas"]["Profile"];
            pack: components["schemas"]["Pack"];
            persona: components["schemas"]["PersonaIn"];
            domain: components["schemas"]["DomainIn"];
            /**
             * Messages
             * @default []
             */
            messages?: components["schemas"]["Message"][];
            /**
             * Elapsedsec
             * @default 0
             */
            elapsedSec?: number;
            /**
             * Code
             * @default
             */
            code?: string;
        };
        /** TurnResult */
        TurnResult: {
            /** Reply */
            reply: string;
            /** Endinterview */
            endInterview: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    turn_v1_interview_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    report_v1_interview_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    generate_v1_packs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacksResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    roadmap_v1_roadmap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    assist_v1_assist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    models_health_v1_health_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsHealth"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsHealth"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
